spring.application.name=taskr
spring.datasource.url=jdbc:postgresql://localhost:5432/taskr
spring.datasource.username=taskr
spring.datasource.password=taskr
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true